Commented out integration tests in CI.

diff --git a/.github/workflows/ynami-cicd.yml b/.github/workflows/ynami-cicd.yml
--- a/.github/workflows/ynami-cicd.yml
+++ b/.github/workflows/ynami-cicd.yml
@@ -95,73 +95,73 @@ jobs:
           name: 'DB Migration Tests'' Report'
           path: ${{ env.UNIT_TESTS_XMLS_DIR }}
 
-  integration-tests-h2:
-    runs-on: ubuntu-22.04
-
-    steps:
-      - name: 'Get the latest code from the `${{ github.repository }}` repository'
-        uses: actions/checkout@v3
-      - name: 'Set up the JDK `${{ env.JAVA_VERSION }}`'
-        uses: './.github/actions/install-java'
-        with:
-          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
-      - name: 'Run the integration tests'
-        run: mvn -Djacoco.skip=true clean integration-test -Dmaven.test.failure.ignore=true -P it,h2 --file pom.xml
-      - name: 'Integration Tests'' with H2 - Summary'
-        if: success() || failure()
-        uses: test-summary/action@v2
-        with:
-          show: "fail"
-          paths: "${{ env.INTEGRATION_TESTS_XMLS_DIR }}"
-#     Intentionally not uploading the H2 tests' result to avoid conflicts with other integration tests run with MySQL
-      - name: 'Report'
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          fail-on-error: true
-          reporter: java-junit
-          name: 'Integration Tests'' Report (H2)'
-          path: ${{ env.INTEGRATION_TESTS_XMLS_DIR }}
-
-  integration-tests-mysql:
-    runs-on: ubuntu-22.04
-
-    steps:
-      - name: 'Get the latest code from the `${{ github.repository }}` repository'
-        uses: actions/checkout@v3
-      - name: 'Set up GitHup runner'
-        uses: './.github/actions/setup-runner'
-        with:
-          WITH_MYSQL: 'TRUE'
-          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
-      - name: 'Run the integration tests'
-        run: mvn -Djacoco.haltOnFailure=false clean integration-test -Dmaven.test.failure.ignore=true -P it,mysql --file pom.xml
-      - name: 'Integration Tests'' with MySQL - Summary'
-        if: success() || failure()
-        uses: test-summary/action@v2
-        with:
-          show: "fail"
-          paths: "${{ env.INTEGRATION_TESTS_XMLS_DIR }}"
-      - name: 'Uploads the results to ${{ env.TESTS_UPLOADED_ARTIFACTS_DIR }} folder'
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.TESTS_UPLOADED_ARTIFACTS_DIR }} # Name of the folder
-          path: target/test-results                     # Path to test report
-      # TODO: Jacoco report for IT isn't correct. It shows the results of the merged report on CI somehow. Uploading the
-      # target/site didn't work sa well, so need to find the issue and fix it properly.
-      - name: 'Uploads the site to ${{ env.UPLOADED_ARTIFACTS_DIR }} folder'
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.UPLOADED_ARTIFACTS_DIR }} # Name of the folder
-          path: target/site                       # Path to test report
-      - name: 'Report'
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          fail-on-error: true
-          reporter: java-junit
-          name: 'Integration Tests'' Report (MySQL)'
-          path: ${{ env.INTEGRATION_TESTS_XMLS_DIR }}
+#  integration-tests-h2:
+#    runs-on: ubuntu-22.04
+#
+#    steps:
+#      - name: 'Get the latest code from the `${{ github.repository }}` repository'
+#        uses: actions/checkout@v3
+#      - name: 'Set up the JDK `${{ env.JAVA_VERSION }}`'
+#        uses: './.github/actions/install-java'
+#        with:
+#          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
+#      - name: 'Run the integration tests'
+#        run: mvn -Djacoco.skip=true clean integration-test -Dmaven.test.failure.ignore=true -P it,h2 --file pom.xml
+#      - name: 'Integration Tests'' with H2 - Summary'
+#        if: success() || failure()
+#        uses: test-summary/action@v2
+#        with:
+#          show: "fail"
+#          paths: "${{ env.INTEGRATION_TESTS_XMLS_DIR }}"
+##     Intentionally not uploading the H2 tests' result to avoid conflicts with other integration tests run with MySQL
+#      - name: 'Report'
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          fail-on-error: true
+#          reporter: java-junit
+#          name: 'Integration Tests'' Report (H2)'
+#          path: ${{ env.INTEGRATION_TESTS_XMLS_DIR }}
+#
+#  integration-tests-mysql:
+#    runs-on: ubuntu-22.04
+#
+#    steps:
+#      - name: 'Get the latest code from the `${{ github.repository }}` repository'
+#        uses: actions/checkout@v3
+#      - name: 'Set up GitHup runner'
+#        uses: './.github/actions/setup-runner'
+#        with:
+#          WITH_MYSQL: 'TRUE'
+#          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
+#      - name: 'Run the integration tests'
+#        run: mvn -Djacoco.haltOnFailure=false clean integration-test -Dmaven.test.failure.ignore=true -P it,mysql --file pom.xml
+#      - name: 'Integration Tests'' with MySQL - Summary'
+#        if: success() || failure()
+#        uses: test-summary/action@v2
+#        with:
+#          show: "fail"
+#          paths: "${{ env.INTEGRATION_TESTS_XMLS_DIR }}"
+#      - name: 'Uploads the results to ${{ env.TESTS_UPLOADED_ARTIFACTS_DIR }} folder'
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ${{ env.TESTS_UPLOADED_ARTIFACTS_DIR }} # Name of the folder
+#          path: target/test-results                     # Path to test report
+#      # TODO: Jacoco report for IT isn't correct. It shows the results of the merged report on CI somehow. Uploading the
+#      # target/site didn't work as well, so need to find the issue and fix it properly.
+#      - name: 'Uploads the site to ${{ env.UPLOADED_ARTIFACTS_DIR }} folder'
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ${{ env.UPLOADED_ARTIFACTS_DIR }} # Name of the folder
+#          path: target/site                       # Path to test report
+#      - name: 'Report'
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          fail-on-error: true
+#          reporter: java-junit
+#          name: 'Integration Tests'' Report (MySQL)'
+#          path: ${{ env.INTEGRATION_TESTS_XMLS_DIR }}
 
   bdd-cucumber-tests:
     runs-on: ubuntu-22.04
@@ -291,4 +291,3 @@ jobs:
         with:
           name: ${{ env.UPLOADED_ARTIFACTS_DIR }} # Name of the folder
           path: target/site                       # Path to test report
-
